### ISSUE TITLE
Post-hook to automatically retrieve template version when generating repository

### ISSUE THREAD

**Issue by BorjaEst** [ai4os/ai4-template#1]
For the moment from here:
https://github.com/ai4os/ai4-template/blob/6acd1ed7798a7da9e1b0176f640adbae2f8dd589/cookiecutter.json#L15

Ideal would be to collect it from tags or releases from the repo/folder used for cloning.

Check it should not do it online as cookiecutter caches templates.

**Comment by vykozlov** [comment]
I don't think cookiecutter pulls whole repository with tags etc while creating a new repo from the template. Taking latest tag from github does not necessarily mean this is the tag a user is using locally, because a user may use cached version. Same holds for the VERSION file
The only solution I currently see, is to have VERSION file and do pre-commit hooks in the cookiecutter git repo itself to update cookiecutter.json. On the other hand, if cookiecutter.json is anyway the only place with the version, there is not much sense for the VERSION file

**Comment by vykozlov** [comment]
but git hooks are not version controlled :-(

**Comment by BorjaEst** [comment]
indeed, I think the simplest is to simply remove the VERSION file

**Comment by vykozlov** [comment]
Finally, implemented GitHub actions:
* if VERSION file in the "main" updated => this re-writes the ai4-template/version in the cookiecutter.json file
See commit 657e996c5a39a758265417dd44fd905b8f36761f and the "version-update" workflow.

may think of creating automatically tags but I am a bit worried if that causes some problems. I'll close the issue for now.
